esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  comment: ${device_comment}

logger:

packages:
  wifi_network: !include network/wifi.yaml
  basic_sensors: !include sensors/basics.yaml

