esphome:
  name: "office-background-lamp"
  friendly_name: Office lamp
  comment: "Lamp that serves as background lighting for late at night at the office"

esp8266:
  board: esp01_1m

# Enable logging
#logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret apikey_office_background_lamp

ota:
  - platform: esphome
    password: !secret otapwd_office_background_lamp

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Office-Lamp Fallback Hotspot"
    password: "L15oz2Rfb2F9"

output:
  - platform: gpio
    pin: GPIO12
    id: relay

text_sensor:
  - platform: version
    name: version

sensor:
  - platform: uptime
    name: "uptime"
    update_interval: 60s

  - platform: wifi_signal
    name: "WiFi signal"
    update_interval: 10s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Physical Button"
    internal: True
    on_press:
      - light.toggle: background_light

light:
  - platform: binary
    id: background_light
    name: "Background light"
    output: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

