external_components:
  - source: github://nrandell/dallasng

# For some reason, dallas had a ton of bugs. Dallasng "just works"
dallasng:
  - pin: ${dallas_pin}
    update_interval: 20s

sensor:
  - platform: dallasng
    address: ${dallas_address}
    name: ${dallas_name}
    resolution: 12
    filters:
      - filter_out: NAN

