substitutions:
  name: everything-presence-lite-2241f8
  friendly_name: EPL1
  device_friendly_name: ${friendly_name}
packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha-no-ble.yaml@main
  wifi_network: !include network/wifi.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret apikey_eplite
